default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: mladizubinpotok_development

test:
  <<: *default
  database: mladizubinpotok_test

production:
  <<: *default
  database: mladizubinpotok_production